Update sync.yml

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -1,15 +1,15 @@
-name: Sync Fork with Upstream
-
-on:
-  schedule:
-    - cron: '0 19 * * *'
-  workflow_dispatch:
+name: Upstream Sync
 
 permissions:
   contents: write
 
+on:
+  schedule:
+    - cron: "0 0 * * *" # every day
+  workflow_dispatch:
+
 jobs:
- sync_latest_from_upstream:
+  sync_latest_from_upstream:
     name: Sync latest commits from upstream repo
     runs-on: ubuntu-latest
     if: ${{ github.event.repository.fork }}
@@ -28,13 +28,13 @@ jobs:
           upstream_sync_branch: main
           target_sync_branch: main
           target_repo_token: ${{ secrets.GITHUB_TOKEN }} # automatically generated, no need to set
-          exclude: |
-            .github/workflows/sync.yml
 
-      - name: Check for errors
+          # Set test_mode true to run tests instead of the true action!!
+          test_mode: false
+
+      - name: Sync check
         if: failure()
-        run: echo "Sync failed! Please check the logs for more details."
-
-      - name: Sync success message
-        if: success()
-        run: echo "Sync completed successfully!"
+        run: |
+          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次，详细教程请查看项目README.md "
+          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork. Please refer to the project README.md for instructions. "
+          exit 1
